openapi: 3.0.3
info:
  description: This document describes the HuBMAP Ontology API
  title: HuBMAP Ontology API
  version: 1.1.4
servers:
- url: https://ontology.api.hubmapconsortium.org/
paths:
  /codes/{code_id}/codes:
    get:
      operationId: codes_code_id_codes_get
      parameters:
      - description: The code identifier
        explode: false
        in: path
        name: code_id
        required: true
        schema:
          example: SNOMEDCT_US 254837009
          type: string
        style: simple
      - description: One or more sources (SABs) to return
        explode: true
        in: query
        name: sab
        required: false
        schema:
          default: []
          items:
            example: NCI,MDR
            type: string
          type: array
          uniqueItems: true
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CodesCodesObj'
                type: array
          description: A JSON array of dictionaries
      summary: Returns a list of code_ids {Concept, Code, SAB} that code the same
        concept(s) as the code_id, optionally restricted to source (SAB)
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /codes/{code_id}/concepts:
    get:
      operationId: codes_code_id_concepts_get
      parameters:
      - description: The code identifier
        explode: false
        in: path
        name: code_id
        required: true
        schema:
          example: SNOMEDCT_US 254837009
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ConceptDetail'
                type: array
          description: A JSON array of dictionaries
      summary: Returns a list of concepts {Concept, Prefterm} that the code_id codes
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/expand:
    post:
      operationId: concepts_expand_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConceptSabRelDepth'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ConceptPrefterm'
                type: array
          description: Return all {concept, prefterm}
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/paths:
    post:
      operationId: concepts_path_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConceptSabRel'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PathItemConceptRelationshipSabPrefterm'
                type: array
          description: Return all paths of the relationship pattern specified within
            the selected sources
      summary: Return all paths of the relationship pattern specified within the selected
        sources
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/trees:
    post:
      operationId: concepts_trees_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConceptSabRelDepth'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PathItemConceptRelationshipSabPrefterm'
                type: array
          description: Return all paths of the relationship pattern specified within
            the selected sources
      summary: Return all paths of the relationship pattern specified within the selected
        sources
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/{concept_id}/codes:
    get:
      operationId: concepts_concept_id_codes_get
      parameters:
      - description: The concept identifier
        explode: false
        in: path
        name: concept_id
        required: true
        schema:
          example: C0678222
          type: string
        style: simple
      - description: One or more sources (SABs) to return
        explode: true
        in: query
        name: sab
        required: false
        schema:
          default: []
          items:
            example: MEDLINEPLUS,MSH,MEDCIN
            type: string
          type: array
          uniqueItems: true
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  example: CHV 0000052645
                  type: string
                type: array
          description: A JSON array of code_id(s) that code the concept
      summary: Returns a distinct list of code_id(s) that code the concept
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/{concept_id}/concepts:
    get:
      operationId: concepts_concept_id_concepts_get
      parameters:
      - description: The concept identifier
        explode: false
        in: path
        name: concept_id
        required: true
        schema:
          example: C0006142
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SabRelationshipConceptPrefterm'
                type: array
          description: A JSON array of {Sab, Relationship, Concept, Prefterm} dictionaries
      summary: Returns a list of concepts {Sab, Relationship, Concept, Prefterm} related
        to the concept
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/{concept_id}/definitions:
    get:
      operationId: concepts_concept_id_definitions_get
      parameters:
      - description: The concept identifier
        explode: false
        in: path
        name: concept_id
        required: true
        schema:
          example: C0006142
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SabDefinition'
                type: array
          description: A JSON array of {Sab, Definition} dictionaries
      summary: Returns a list of definitions {Sab, Definition} of the concept
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/{concept_id}/semantics:
    get:
      operationId: concepts_concept_id_semantics_get
      parameters:
      - description: The concept identifier
        explode: false
        in: path
        name: concept_id
        required: true
        schema:
          example: C0304055
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/StyTuiStn'
                type: array
          description: A JSON array of {Sty, Tui, Stn} dictionaries
      summary: Returns a list of semantic_types {Sty, Tui, Stn} of the concept
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /semantics/{semantic_id}/semantics:
    get:
      operationId: semantics_semantic_id_semantics_get
      parameters:
      - description: The semantic identifier
        explode: false
        in: path
        name: semantic_id
        required: true
        schema:
          example: Physical Object
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/QQST'
                type: array
          description: A JSON array of {queryTUI, querySTN ,semantic, TUI_STN} dictionaries
      summary: Returns a list of semantic_types {queryTUI, querySTN ,semantic, TUI_STN}
        of the semantic type
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /terms/{term_id}/codes:
    get:
      operationId: terms_term_id_codes_get
      parameters:
      - description: The term identifier
        explode: false
        in: path
        name: term_id
        required: true
        schema:
          example: Breast cancer
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TermtypeCode'
                type: array
          description: A JSON array of {TermType, Code} dictionaries
      summary: Returns a list of codes {TermType, Code} of the text string
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /terms/{term_id}/concepts:
    get:
      operationId: terms_term_id_concepts_get
      parameters:
      - description: The term identifier
        explode: false
        in: path
        name: term_id
        required: true
        schema:
          example: Breast cancer
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  example: C0794811
                  type: string
                type: array
          description: A JSON array of concepts associated with the term
      summary: Returns a list of concepts associated with the text string
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /terms/{term_id}/concepts/terms:
    get:
      operationId: terms_term_id_concepts_terms_get
      parameters:
      - description: The term identifier
        explode: false
        in: path
        name: term_id
        required: true
        schema:
          example: Breast cancer
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ConceptTerm'
                type: array
          description: A JSON array of {Concept, Term} dictionaries
      summary: Returns an expanded list of concept(s) and preferred term(s) {Concept,
        Term} from an exact text match
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /tui/{tui_id}/semantics:
    get:
      operationId: tui_tui_id_semantics_get
      parameters:
      - description: The TUI identifier
        explode: false
        in: path
        name: tui_id
        required: true
        schema:
          example: T200
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SemanticStn'
                type: array
          description: A JSON array of {semantic, STN} dictionaries
      summary: Returns a list of symantic_types {semantic, STN} of the type unique
        id (tui)
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    CodesCodesObj:
      example:
        code: CCS 2.5
        SAB: CCF
        concept: C0006142
      properties:
        concept:
          example: C0006142
          title: concept
          type: string
        code:
          example: CCS 2.5
          title: code
          type: string
        SAB:
          example: CCF
          title: SAB
          type: string
      title: CodesCodesObj
      type: object
    ConceptDetail:
      example:
        concept: C0006142
        prefterm: Malignant neoplasm of breast
      properties:
        concept:
          example: C0006142
          title: concept
          type: string
        prefterm:
          example: Malignant neoplasm of breast
          title: prefterm
          type: string
      title: ConceptDetail
      type: object
    ConceptSabRel:
      example:
        sab:
        - SNOMEDCT_US
        - HGNC
        rel:
        - isa
        - isa
        query_concept_id: C2720507
      properties:
        query_concept_id:
          example: C2720507
          type: string
        sab:
          example:
          - SNOMEDCT_US
          - HGNC
          items:
            type: string
          type: array
        rel:
          example:
          - isa
          - isa
          items:
            type: string
          type: array
      type: object
    ConceptSabRelDepth:
      example:
        depth: 2
        sab:
        - SNOMEDCT_US
        - HGNC
        rel:
        - isa
        - isa
        query_concept_id: C2720507
      properties:
        query_concept_id:
          example: C2720507
          type: string
        sab:
          example:
          - SNOMEDCT_US
          - HGNC
          items:
            type: string
          type: array
        rel:
          example:
          - isa
          - isa
          items:
            type: string
          type: array
        depth:
          example: 2
          type: integer
      type: object
    ConceptPrefterm:
      example:
        concept: C0006826
        prefterm: Malignant Neoplasms
      properties:
        concept:
          example: C0006826
          title: concept
          type: string
        prefterm:
          example: Malignant Neoplasms
          title: prefterm
          type: string
      title: ConceptPrefterm
      type: object
    ConceptTerm:
      example:
        concept: C0006826
        term: LNC LA14283-8
      properties:
        concept:
          example: C0006826
          title: concept
          type: string
        term:
          example: LNC LA14283-8
          title: term
          type: string
      title: ConceptTerm
      type: object
    PathItemConceptRelationshipSabPrefterm:
      example:
        path: path
        item: item
        sab: ICD10AM
        concept: C0006826
        prefterm: Malignant Neoplasms
        relationship: CHD
      properties:
        path:
          title: path
          type: string
        item:
          title: item
          type: string
        concept:
          example: C0006826
          title: concept
          type: string
        relationship:
          example: CHD
          title: relationship
          type: string
        sab:
          example: ICD10AM
          title: sab
          type: string
        prefterm:
          example: Malignant Neoplasms
          title: prefterm
          type: string
      title: PathItemConceptRelationshipSabPrefterm
      type: object
    QQST:
      example:
        semantic: Entity
        querySTN: A1
        queryTUI: T072
        TUI: T071
        STN: A
      properties:
        queryTUI:
          example: T072
          title: queryTUI
          type: string
        querySTN:
          example: A1
          title: querySTN
          type: string
        semantic:
          example: Entity
          title: semantic
          type: string
        TUI:
          example: T071
          title: TUI
          type: string
        STN:
          example: A
          title: STN
          type: string
      title: QQST
      type: object
    SabDefinition:
      example:
        sab: NCI
        definition: A primary or metastatic malignant neoplasm involving the breast.
          The vast majority of cases are carcinomas arising from the breast parenchyma
          or the nipple. Malignant breast neoplasms occur more frequently in females
          than in males.
      properties:
        sab:
          example: NCI
          title: sab
          type: string
        definition:
          example: A primary or metastatic malignant neoplasm involving the breast.
            The vast majority of cases are carcinomas arising from the breast parenchyma
            or the nipple. Malignant breast neoplasms occur more frequently in females
            than in males.
          title: definition
          type: string
      title: SabDefinition
      type: object
    SabRelationshipConceptPrefterm:
      example:
        sab: ICD10AM
        concept: C0006826
        prefterm: Malignant Neoplasms
        relationship: CHD
      properties:
        sab:
          example: ICD10AM
          title: sab
          type: string
        relationship:
          example: CHD
          title: relationship
          type: string
        concept:
          example: C0006826
          title: concept
          type: string
        prefterm:
          example: Malignant Neoplasms
          title: prefterm
          type: string
      title: SabRelationshipConceptPrefterm
      type: object
    SemanticStn:
      example:
        semantic: Entity
        STN: A
      properties:
        semantic:
          example: Entity
          title: semantic
          type: string
        STN:
          example: A
          title: STN
          type: string
      title: SemanticStn
      type: object
    StyTuiStn:
      example:
        sty: Organic Chemical
        tui: T109
        stn: A1.4.1.2.1
      properties:
        sty:
          example: Organic Chemical
          title: sty
          type: string
        tui:
          example: T109
          title: tui
          type: string
        stn:
          example: A1.4.1.2.1
          title: stn
          type: string
      title: StyTuiStn
      type: object
    TermtypeCode:
      example:
        code: LNC LA14283-8
        termtype: LA
      properties:
        termtype:
          example: LA
          title: termtype
          type: string
        code:
          example: LNC LA14283-8
          title: code
          type: string
      title: TermtypeCode
      type: object
